### ISSUE TITLE
P110M error

### ISSUE THREAD

**Issue by sanzoku12** [mihai-dinculescu/tapo#401]
Hello,

Thank you for great library.

Today error occurred at "device_info = await device.get_device_info()" for P110M. It, however, used to work fine for P110M, and it also works fine for P100 still now. So could you give me some advice, please.

D:\>python ".\tapo_util_sw.py"
Traceback (most recent call last):
  File "D:\tapo_util_sw.py", line 34, in <module>
    asyncio.run(main())
  File "C:\Users\userxxxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\userxxxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\userxxxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\tapo_util_sw.py", line 19, in main
    device_info = await device.get_device_info()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Serde(Error("missing field `state`", line: 1, column: 693))

my device with error is,
Tapo P110M
1.3.2 Build 250526 Rel 171305

**Comment by mihai-dinculescu** [comment]
The fix was released in v0.8.4. Thank you for reporting this issue!

**Comment by sanzoku12** [comment]
Thanks in advance and I tried V0.8.4 but it still not work for P110M. The following is my log. Could you give me some advice?


D:\>python tapo_util_sw.py
DEBUG:tapo.api.api_client:Device url: http://192.168.XXX.XXX/app
DEBUG:tapo.api.protocol.discovery_protocol:Testing the Passthrough protocol...
DEBUG:tapo.api.protocol.discovery_protocol:Component negotiation request: {"method":"component_nego","params":null}
DEBUG:reqwest.connect:starting new connection: http://192.168.XXX.XXX
DEBUG:tapo.api.protocol.discovery_protocol:Device responded with: TapoResponse { error_code: 1003, result: None }
DEBUG:tapo.api.protocol.discovery_protocol:Not supported. Setting up the Klap protocol...
DEBUG:tapo.api.protocol.klap_protocol:Performing handshake1...
DEBUG:tapo.api.protocol.klap_protocol:Handshake1 OK
DEBUG:tapo.api.protocol.klap_protocol:Performing handshake2...
DEBUG:tapo.api.protocol.klap_protocol:Handshake2 OK
DEBUG:tapo.api.api_client:Get Device info...
DEBUG:tapo.api.protocol.klap_protocol:Request: {"method":"get_device_info","params":null}
Level 5:tapo.api.protocol.klap_protocol:Device responded with (raw): {"result":{"device_id":"XXXXXXXXXXXXXXXXA51D8E6B1B9879E321E8XXXX","fw_ver":"1.3.2 Build 250526 Rel.171305","hw_ver":"1.0","type":"SMART.TAPOPLUG","model":"P110M","mac":"XX-XX-XX-34-CF-XX","hw_id":"XXXXXXXXXXXXXXXXFDB8BA6F6313XXXX","fw_id":"00000000000000000000000000000000","oem_id":"XXXXXXXXXXXX9990A03EF5503991XXXX","ip":"192.168.XXX.XXX","time_diff":540,"ssid":"YXRlcm0tY2U1ZDA5LWc=","rssi":-52,"signal_level":2,"auto_off_status":"off","auto_off_remain_time":0,"longitude":XX977XX,"latitude":XX72XX,"lang":"ja_JP","avatar":"plug","region":"Asia/Tokyo","specs":"JP","nickname":"XXXXXXKZ5pXX","has_set_location_info":true,"device_on":false,"on_time":0,"default_states":{"type":"last_states"},"power_protection_status":"normal","overcurrent_status":"normal","charging_status":"normal"},"error_code":0}
Traceback (most recent call last):
  File "D:\tapo_util_sw.py", line 38, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "D:\tapo_util_sw.py", line 23, in main
    device_info = await device.get_device_info()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Serde(Error("missing field `state`", line: 1, column: 691))

**Comment by mihai-dinculescu** [comment]
Please do triple-check that you're using the latest version.

With the same JSON as the one that you have, it deserialises fine for me.

```bash
2025-08-22T20:02:46.517Z DEBUG tapo::api::api_client                   > Get Device info...
 2025-08-22T20:02:46.518Z DEBUG tapo::api::protocol::klap_protocol      > Request: {"method":"get_device_info","params":null}
 2025-08-22T20:02:46.538Z TRACE tapo::api::protocol::klap_protocol      > Device responded with (raw): {"result":{"device_id":"80221C733407C6413A3BDE090B845FAF22248DFE","fw_ver":"1.3.2 Build 250526 Rel.171305","hw_ver":"1.0","type":"SMART.TAPOPLUG","model":"P110M","mac":"E4-FA-C4-EB-54-DB","hw_id":"E2B8338B0C506D476C4483D3377F1D54","fw_id":"00000000000000000000000000000000","oem_id":"BFB971D4927F4FCF9B6383B8C7AE390D","ip":"192.168.1.115","time_diff":0,"ssid":"UmVhbWRl","rssi":-49,"signal_level":3,"auto_off_status":"off","auto_off_remain_time":0,"longitude":1242,"latitude":520960,"lang":"en_US","avatar":"plug","region":"Europe/London","specs":"","nickname":"T2ZmaWNlIEhlYXRlcg==","has_set_location_info":true,"device_on":false,"on_time":0,"default_states":{"type":"last_states"},"power_protection_status":"normal","overcurrent_status":"normal","charging_status":"normal"},"error_code":0}
 2025-08-22T20:02:46.538Z DEBUG tapo::api::protocol::klap_protocol      > Device responded with: TapoResponse { error_code: 0, result: Some(DeviceInfoPlugEnergyMonitoringResult { device_id: "80221C733407C6413A3BDE090B845FAF22248DFE", type: "SMART.TAPOPLUG", model: "P110M", hw_id: "E2B8338B0C506D476C4483D3377F1D54", hw_ver: "1.0", fw_id: "00000000000000000000000000000000", fw_ver: "1.3.2 Build 250526 Rel.171305", oem_id: "BFB971D4927F4FCF9B6383B8C7AE390D", mac: "E4-FA-C4-EB-54-DB", ip: "192.168.1.115", ssid: "UmVhbWRl", signal_level: 3, rssi: -49, specs: "", lang: "en_US", device_on: false, on_time: 0, nickname: "T2ZmaWNlIEhlYXRlcg==", avatar: "plug", has_set_location_info: true, region: Some("Europe/London"), latitude: Some(520960), longitude: Some(1242), time_diff: Some(0), charging_status: Normal, default_states: LastStates, overcurrent_status: Normal, overheat_status: None, power_protection_status: Normal }) }
 2025-08-22T20:02:46.539Z INFO  tapo_p110                               > Device info: DeviceInfoPlugEnergyMonitoringResult { device_id: "80221C733407C6413A3BDE090B845FAF22248DFE", type: "SMART.TAPOPLUG", model: "P110M", hw_id: "E2B8338B0C506D476C4483D3377F1D54", hw_ver: "1.0", fw_id: "00000000000000000000000000000000", fw_ver: "1.3.2 Build 250526 Rel.171305", oem_id: "BFB971D4927F4FCF9B6383B8C7AE390D", mac: "E4-FA-C4-EB-54-DB", ip: "192.168.1.115", ssid: "Reamde", signal_level: 3, rssi: -49, specs: "", lang: "en_US", device_on: false, on_time: 0, nickname: "Office Heater", avatar: "plug", has_set_location_info: true, region: Some("Europe/London"), latitude: Some(520960), longitude: Some(1242), time_diff: Some(0), charging_status: Normal, default_states: LastStates, overcurrent_status: Normal, overheat_status: None, power_protection_status: Normal }
```

**Comment by sanzoku12** [comment]
I made a trivial mistake, but finally the 0.8.4 for P110M works fine. I appreciate your help.
